# Generated by Django 5.2.4 on 2025-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0002_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="constraints",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="input_format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="output_format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="verdict",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
