# Generated by Django 5.2.4 on 2025-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0003_problem_constraints_problem_input_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
