# Generated by Django 5.2.4 on 2025-07-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0004_submission_error_submission_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="sample_input",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="sample_output",
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=True)),
                ("is_custom", models.BooleanField(default=False)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="judge.problem",
                    ),
                ),
            ],
        ),
    ]
