# Generated by Django 5.2.4 on 2025-07-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0005_remove_problem_sample_input_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="constraints",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="is_custom",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="is_sample",
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="test_results_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="passed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(default="Easy", max_length=50),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("cpp", "C++"), ("java", "Java")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="verdict",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
